SET SQL_SAFE_UPDATES = 0;

INSERT INTO CATEGORIES VALUE(0, 'CATE_A');
INSERT INTO CATEGORIES VALUE(0, 'CATE_B');
INSERT INTO CATEGORIES VALUE(0, 'CATE_C');
INSERT INTO CATEGORIES VALUE(0, 'CATE_D');


INSERT INTO CONSOLES VALUE(0, 'CONSOLE_A');
INSERT INTO CONSOLES VALUE(0, 'CONSOLE_B');
INSERT INTO CONSOLES VALUE(0, 'CONSOLE_C');
INSERT INTO CONSOLES VALUE(0, 'CONSOLE_D');


INSERT INTO GAMES(GAME_ID, TITLE) VALUE(0, 'GAME_A');
INSERT INTO GAMES(GAME_ID, TITLE) VALUE(0, 'GAME_B');
INSERT INTO GAMES(GAME_ID, TITLE) VALUE(0, 'GAME_C');
INSERT INTO GAMES(GAME_ID, TITLE) VALUE(0, 'GAME_D');


INSERT INTO USERS(USER_ID, USER_NAME) VALUE(0, 'USER_A');
INSERT INTO USERS(USER_ID, USER_NAME) VALUE(0, 'USER_B');
INSERT INTO USERS(USER_ID, USER_NAME) VALUE(0, 'USER_C');
INSERT INTO USERS(USER_ID, USER_NAME) VALUE(0, 'USER_D');


INSERT INTO ORDERS(ORDER_ID, CONSOLE_ID, USER_ID, GAME_ID) VALUE(0, 1, 1000001, 2);
INSERT INTO ORDERS(ORDER_ID, CONSOLE_ID, USER_ID, GAME_ID) VALUE(0, 1, 1000001, 1);


INSERT INTO PUBLISHERS(PUBLISHER_ID, PUBLISHER_NAME) VALUE(0, 'PUBLISHER_A');
INSERT INTO PUBLISHERS(PUBLISHER_ID, PUBLISHER_NAME) VALUE(0, 'PUBLISHER_B');
INSERT INTO PUBLISHERS(PUBLISHER_ID, PUBLISHER_NAME) VALUE(0, 'PUBLISHER_C');
INSERT INTO PUBLISHERS(PUBLISHER_ID, PUBLISHER_NAME) VALUE(0, 'PUBLISHER_D');


INSERT INTO REVIEWS(REVIEW_ID, CONTENT) VALUE(0, 'This is review A');
INSERT INTO REVIEWS(REVIEW_ID, CONTENT) VALUE(0, 'This is review B');
INSERT INTO REVIEWS(REVIEW_ID, CONTENT) VALUE(0, 'This is review C');
INSERT INTO REVIEWS(REVIEW_ID, CONTENT) VALUE(0, 'This is review D');


INSERT INTO TAGS VALUE(0, 'TAG_A');
INSERT INTO TAGS VALUE(0, 'TAG_B');
INSERT INTO TAGS VALUE(0, 'TAG_C');
INSERT INTO TAGS VALUE(0, 'TAG_D');

DELETE FROM USERS
where user_id = 1000001;
